# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#   Powershell:
#     Psini: 3.1.3
#
#  Name:
#    spl_change_builtin_indexes.yml
#
#  Description:
#    Changing frozenTimePeriodInSecs option of each built-in index
#    Use spl_idxc_change_builtin_indexes.yml for indexer cluster member(s)
#
#  Input:
#    spl_home_dir # Path to Splunk home dir; Default 'C:\Program Files\Splunk'; Taken from inventory
#    spl_index_frozen_in_secs # Number of seconds after which indexed data rolls to frozen
#    spl_skip_restart # 1 - yes; 0 - no; Restart is required but you can skip it
#
#  Output:
#    -
#
#  Requirements:
#    Expected to run on server(s) which are not selected as cluster member
#    Powershell module:
#      Psini

---

- name: 'SPL :: Changing  {{ spl_home_dir }}\etc\system\local\indexes.conf'
  include_tasks: ../ansible_play/windows/windows_edit_ini.yml
  vars:
    ini_section: '{{ item.section }}'
    ini_option: 'frozenTimePeriodInSecs'
    ini_value: '{{ spl_index_frozen_in_secs }}'
    ini_path: '{{ spl_home_dir }}\etc\system\local\indexes.conf'
    ini_mode: 'set'
  loop:
    - { section: '_audit'}
    - { section: '_configtracker'}
    - { section: '_internal'}
    - { section: '_introspection'}
    - { section: '_metrics'}
    - { section: '_metrics_rollup'}
    - { section: '_telemetry'}
    - { section: '_thefishbucket'}
    - { section: 'main'}
    - { section: 'splunklogger'}
    - { section: 'summary'}
  loop_control:
    index_var: loop_idx

- import_tasks: ./spl_manage_service.yml
  vars:
    spl_service_action: 'restart'
  when: spl_skip_restart == 0